//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace newcustomers_Limena.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_NewCustomers
    {
        public int ID_customer { get; set; }
        public string CardName { get; set; }
        public string Phone1 { get; set; }
        public string E_Mail { get; set; }
        public string IntrntSite { get; set; }
        public string TAXID { get; set; }
        public string TAXCERTNUM { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Position { get; set; }
        public string Tel1 { get; set; }
        public string E_MailL { get; set; }
        public string Street { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string ZipCode { get; set; }
        public string Country { get; set; }
        public string StoreServices { get; set; }
        public string Etnias { get; set; }
        public string url_imageTAXCERT { get; set; }
        public string url_imageTAXCERNUM { get; set; }
        public string OperationTime { get; set; }
        public string ReciboMercaderia_dia { get; set; }
        public string ReciboMercaderia_area { get; set; }
        public bool Muelle_descarga { get; set; }
        public string Store_size { get; set; }
        public bool Validated { get; set; }
        public bool OnSharepoint { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> Supervisor { get; set; }
        public string urlsharepoint { get; set; }
        public Nullable<int> idsharepoint { get; set; }
        public Nullable<int> idRep { get; set; }
        public Nullable<int> idSAPRep { get; set; }
        public string emailRep { get; set; }
    }
}
