//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace newcustomers_Limena.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UFD1
    {
        public string TableID { get; set; }
        public short FieldID { get; set; }
        public short IndexID { get; set; }
        public string FldValue { get; set; }
        public string Descr { get; set; }
        public Nullable<System.DateTime> FldDate { get; set; }
    }
}
